export const IMAGES = {
  welcomeScreen: document.getElementById("welcomeScreen"),
  // props
  coin: document.getElementById("coin"),
  key: document.getElementById("key"),
  heart: document.getElementById("heart-xsmall"),
  chest: document.getElementById("chest"),
  jelly: document.getElementById("jelly"),
  signRight: document.getElementById("signRight"),
  signLeft: document.getElementById("signLeft"),
  // SECRET MESSAGE PARTS
  secretMessage: {
    1: document.getElementById("messagePart1"),
    2: document.getElementById("messagePart2"),
    3: document.getElementById("messagePart3"),
    4: document.getElementById("messagePart4"),
  },
  // BACKGROUND LAYERS
  layer1: document.getElementById("layer1"),
  layer2: document.getElementById("layer2"),
  layer3: document.getElementById("layer3"),
  layer4: document.getElementById("layer4"),
  layer5: document.getElementById("layer5"),
  layer6: document.getElementById("layer6"),
  layer7: document.getElementById("layer7"),
  // SLIME
  slime: [
    document.getElementById("slime0"),
    document.getElementById("slime1"),
    document.getElementById("slime2"),
    document.getElementById("slime3"),
    document.getElementById("slime4"),
    document.getElementById("slime5"),
    document.getElementById("slime6"),
    document.getElementById("slime7"),
    document.getElementById("slime8"),
    document.getElementById("slime9"),
    document.getElementById("slime10"),
    document.getElementById("slime11"),
    document.getElementById("slime12"),
    document.getElementById("slime13"),
    document.getElementById("slime14"),
    document.getElementById("slime15"),
    document.getElementById("slime16"),
    document.getElementById("slime17"),
    document.getElementById("slime18"),
    document.getElementById("slime19"),
    document.getElementById("slime20"),
    document.getElementById("slime21"),
    document.getElementById("slime22"),
    document.getElementById("slime23"),
    document.getElementById("slime24"),
    document.getElementById("slime25"),
    document.getElementById("slime26"),
    document.getElementById("slime27"),
    document.getElementById("slime28"),
    document.getElementById("slime29"),
  ],

  // PLAYER
  player: {
    idle: [
      document.getElementById("flatBoyIdle1"),
      document.getElementById("flatBoyIdle2"),
      document.getElementById("flatBoyIdle3"),
      document.getElementById("flatBoyIdle4"),
      document.getElementById("flatBoyIdle5"),
      document.getElementById("flatBoyIdle6"),
      document.getElementById("flatBoyIdle7"),
      document.getElementById("flatBoyIdle8"),
      document.getElementById("flatBoyIdle9"),
      document.getElementById("flatBoyIdle10"),
      document.getElementById("flatBoyIdle11"),
      document.getElementById("flatBoyIdle12"),
      document.getElementById("flatBoyIdle13"),
      document.getElementById("flatBoyIdle14"),
      document.getElementById("flatBoyIdle15"),
    ],
    run: [
      document.getElementById("flatBoyRun1"),
      document.getElementById("flatBoyRun2"),
      document.getElementById("flatBoyRun3"),
      document.getElementById("flatBoyRun4"),
      document.getElementById("flatBoyRun5"),
      document.getElementById("flatBoyRun6"),
      document.getElementById("flatBoyRun7"),
      document.getElementById("flatBoyRun8"),
      document.getElementById("flatBoyRun9"),
      document.getElementById("flatBoyRun10"),
      document.getElementById("flatBoyRun11"),
      document.getElementById("flatBoyRun12"),
      document.getElementById("flatBoyRun13"),
      document.getElementById("flatBoyRun14"),
      document.getElementById("flatBoyRun15"),
    ],
    jump: document.getElementById("flatBoyJump7"),
  },
};
